[package]
name = "vtop"
version = "0.1.0"
authors = ["kvvarun-mecha <varunkkv.mec@gmail.com>"]
license = "MIT"
edition = "2024"

[dependencies]
crossterm = "0.29.0"
ratatui = "0.29.0"
color-eyre = "0.6.3"
sysinfo = "0.35.0"
